### PR TITLE
Updates to support UWP discovery in TestPlatform v2

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by azchohfi** [comment]
Is this PR a WIP? I tried building it but I'm getting:
```
Utility\DiaSessionWrapperHelper_DotNet.cs(65,53): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Users\alzollin\source\repos\xunit\src\x
unit.runner.utility\xunit.runner.utility.csproj]
Utility\DiaSession.cs(63,29): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Users\alzollin\source\repos\xunit\src\xunit.runner.utility\
xunit.runner.utility.csproj]
```
Weirdly, AppVeyor seems to be building just fine.

**Comment by azchohfi** [comment]
Still same error when building, and when I try to use the **_somehow_** builded nuget packages, I get:
The element <None> beneath element <Otherwise> is unrecognized.  C:\Users\alzollin\.nuget\packages\xunit.runner.visualstudio\2.4.0-beta1-build3925\build\uap10.0\xunit.runner.visualstudio.props
I tried putting it under an ItemsGroup, and then it complains about UnitTestPlatformVersion = "" so comparison between string and number (<When Condition="'$(UnitTestPlatformVersion)' &gt;= '15.5' ">).
Forcing it to use the Other wise at least allows me to open the project, but I still get:
```
[1/25/2018 11:26:24 AM Informational] [xUnit.net 00:00:00.0061152] xUnit.net VSTest Adapter v2.4.0-beta1-build3925 (32-bit Universal Windows)
[1/25/2018 11:26:24 AM Warning] [xUnit.net 00:00:00.0723665] Skipping: PROJECT (Could not find/load any of the following assemblies: xunit.execution.dotnet.dll, xunit.execution.MonoAndroid.dll, xunit.execution.MonoTouch.dll, xunit.execution.iOS-Universal.dll, xunit.execution.universal.dll, xunit.execution.win8.dll, xunit.execution.wp8.dll)
[1/25/2018 11:26:24 AM Warning] [xUnit.net 00:00:00.0890192] Skipping: PROJECT (Could not find/load any of the following assemblies: xunit.execution.dotnet.dll, xunit.execution.MonoAndroid.dll, xunit.execution.MonoTouch.dll, xunit.execution.iOS-Universal.dll, xunit.execution.universal.dll, xunit.execution.win8.dll, xunit.execution.wp8.dll)
[1/25/2018 11:26:24 AM Informational] [xUnit.net 00:00:00.0017590] xUnit.net VSTest Adapter v2.4.0-beta1-build3925 (32-bit Desktop .NET 4.0.30319.42000)
```

**Comment by azchohfi** [comment]
BTW, I'm using VS 2017 15.5.5 (released today).

**Comment by onovotny** [comment]
I'm not sure what you're trying to do here exactly? This right now is about getting TPv2 working with UWP. Can't say it's 100% ready yet.

**Comment by onovotny** [comment]
It does build though

**Comment by azchohfi** [comment]
I'm trying to create an xunit project for UWP, so I'm just trying to use this before it's merged to master. No worries, it's probably my unstable build env.

**Comment by onovotny** [comment]
@azchohfi for now, I'd use the released bits. Just create a new UWP "UnitTestApp" using the MSTest templates, remove the two MSTest NuGet packages and add xunit and the runner. Should work in some cases...the UWP has been unstable, hence this work.

Alternatively you can use the xunit for Devices templates. Makes it really easy to get started:

https://marketplace.visualstudio.com/items?itemName=onovotny.xunitfordevicestemplates

File -> New Project, UWP -> xunit for devices.

**Comment by azchohfi** [comment]
@onovotny 
> That one currently doesn't support the Test Explorer window, but I'm hoping to make them work together.

That's exactly what I was hopping to get from this branch. No hurry. Thanks.

**Comment by bradwilson** [comment]
Running `dotnet restore` (which is used by `build.ps1`) now results in a restore error, because `test.harness.uwp` is not an SDK-style CSPROJ file. Can you please update this so the restore does not have errors?

**Comment by bradwilson** [comment]
I was hoping you'd use an SDK-style CSPROJ, not MSBuild. ;)

**Comment by onovotny** [comment]
Can't do that for "head"/app projects yet, AFAIK.

**Comment by onovotny** [comment]
Needs project system support to launch the correct debugger

**Pull request merged**
