### PR TITLE
Optimize performance of message dispatching

### PR DESCRIPTION
**Pull request by marcind**

### CODE REVIEW

**Comment by jcansdale** [comment]
I've head good things about this PR. Curious where the perf gains mostly came from? :smile:

**Comment by marcind** [comment]
1. Attempting to cast a marshalled object to a specific interface is expensive. The old implementation received a message and then tried a cast using 30ish different interfaces. New code passes a list of implemented interfaces into the visitor, which it can use to do a "type check" before attempting the cast. This has the largest benefit when AppDomains are used, but even without them the perf gets better.
2. The old code implemented default no-op handlers for every type of message. New code switches to events, thus being able to detect if the visitor cares about a particular type of message. The cast in 1) is only attempted if there's a handler that will react to the message.

**Comment by marcind** [comment]
Also, this addresses #472

**Comment by jcansdale** [comment]
Interesting, thanks for the explanation! :rocket:

**Comment by bradwilson** [comment]
Merged, thanks!

**Pull request closed without merging**
