### PR TITLE
Added functionality to honor CollectSourceInformation flag from RunSettings XML

### PR DESCRIPTION
**Pull request by Shyam-Gupta**
Refer RFC: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0010-Source-Information-For-Discovered-Tests.md

Summary:
CollectSourceInformation = True => Test adapter needs to collect source information for the discovered tests
CollectSourceInformation = False => Test adapter doesn't need to collect source information for discovered tests. In case tests are executed from VS IDE, then Test Window will get this information using Roslyn.

By default CollectSourceInformation will be true. It will be false when:
1. VS IDE determines that it can get this information from Roslyn
2. Command line scenario: When tests are executed from vstest.console.exe, this flag will always be false unless user explicitly overrides it in the runsettings XML file.

### CODE REVIEW

**Comment by onovotny** [comment]
Why was `ReporterSwitch` removed?

**Comment by Shyam-Gupta** [comment]
@onovotny 
ReporterSwitch was already in commented out state. Its only indentation changes which came in automatically by VS.

**Comment by bradwilson** [comment]
I cleaned up the RunSettingsHelper class, including enabling ReporterSwitch (understanding that nobody's listening to it yet, but that shouldn't matter).

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
