### PR TITLE
Update MyGet links to use HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by sharwell**
Fixes the following message in Visual Studio 15.8 Preview 2:

> Error occurred while restoring NuGet packages: Unable to get repository signature information for source https://www.myget.org/F/xunit/api/v3/repository-signatures/index.json.

📝 If accepted, please do not rebase or squash this pull request during the merge.

### CODE REVIEW

**Comment by onovotny** [comment]
Okay...can I ask what the issue is?

**Comment by sharwell** [comment]
> Okay...can I ask what the issue is?

It's a strong personal preference which I've requested GitHub account for in their **Allow edits from maintainers** checkbox. Other merge policies are disruptive to my workflows so I avoid sending pull requests to projects that don't allow "normal" merges. I'll file an issue instead.

**Comment by onovotny** [comment]
I'm not sure how a squash/rebase into master, a branch that non-maintainers cannot commit to, would be disruptive? After the merge, it's the same commands either way, checkout master, then pull...

I would like to understand how it's disruptive, what am I missing?

**Comment by sharwell** [comment]
Either way, this is a duplicate of #1741 :wink:

We can chat on Gitter about workflows if you want. :smile:

**Comment by onovotny** [comment]
@sharwell that other PR does too much, not sure why we need to clear/avoid the machine config.

**Pull request closed without merging**
