### PR TITLE
better documentation to avoid issue #695

### PR DESCRIPTION
**Pull request by jongleur1983**
make clear in the documentation that MemberDataAttribute should not return the same objects twice.

### CODE REVIEW

**Comment by bradwilson** [comment]
This documentation is incomplete, because the rule in question applies to _**all**_ data attributes, which means it should probably be placed on DataAttribute itself as well as all derived attributes.

**Comment by jongleur1983** [comment]
good point, will look into it later.

**Comment by jongleur1983** [comment]
? How can that commit that added only comments lead to a failure of teamcity? Sorry, don't understand what's wrong there, sorry in case my commits are causing the trouble, but it would be great if someone could tell me if I did something wrong or how to solve it.

**Comment by onovotny** [comment]
Your commit didn't break the build; VS 2015 Update 1 on the build box is causing the RefactoringEssentials analyzer package to throw and is thus breaking the build.

**Comment by jongleur1983** [comment]
good to know, thanks

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
