### PR TITLE
Provide a suitable value for the class fixture mapping if its constru…

### PR DESCRIPTION
**Pull request by sdelarosbil**
…ctor throws

It allows the mapping to exist such that we aren't pushing more exceptions due to not detecting the arguments later

This one is rather complex to explain and I am open to review should the fix not be proper, but basically, let's say the fixture class's constructor throws, it prevents the test class's constructor from having an entry in its `ClassFixtureMappings`. This means that later on, during `CreateTestClassConstructorArguments`, it will seem like we didn't provided any arguments needed to the constructor of the test class because it will find the constructor, but not its instance mapping during `TryGetConstructorArgument`. This results in a misleading exception being thrown because it looks like as if the argument was missing when the instance was never in the mappings in the first place.

I am relatively unfamiliar with this project, but I feel fixing this is sort of a catch 22: we would want the mapping to exist so it can proceed without throwing further, but it technically isn't correct because the throw makes the fixture invalid. The only way I found to reliably make it work was to assign the mapping to new object. I fear it might be confusing or not proper so I would at least like someone to review if this would be a proper fix. If not, hopefully I provided enough information to figure out a better way to address this.

### CODE REVIEW

**Comment by bradwilson** [comment]
Yeah, this is odd.

For sure, throwing two errors here is wrong, because we shouldn't be trying to map constructor arguments at all, since we know all the tests will fail. I'm not 100% sure that the right way to skip that behavior is what you're doing here; it works, but as you point out, this is something we shouldn't be doing anyways. I want to peek around inside the code to see if there is something better we can do instead.

**Comment by bradwilson** [comment]
I found a way that I like a little better. I've skipped constructor argument matching when the exception aggregator already has exceptions in it, since there's no point (we won't be creating anything, since all tests will be implicitly failed). This not only stops the extra exception, it skips work that's pointless. 😄 

Aside: The new CLA bot has triggered for this PR, though I'm not sure that's necessarily appropriate given the size of the change. I have a question in to the team about why the [minimum line change setting of 8](https://github.com/xunit/.github/blob/9c9d2d4a61f774dc1cffa49164875c21981e334d/policies/cla.yml#L10) seems to be ignored by the bot in this case. If you're okay signing the CLA, then please feel free to do so; if you're not comfortable with it, then just say so here and I'll merge the PR anyways. 😁 Hopefully the team can get back to me on why this happened.

**Comment by sdelarosbil** [comment]
> @sdelarosbil please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree company="Spiria Digital"

**Comment by sdelarosbil** [comment]
It seems I forgot to refference the issue that it closes, #2342

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
