### PR TITLE
Fix Json config to honor -1 maxParallelThreads

### PR DESCRIPTION
**Pull request by BrennanConroy**
https://github.com/xunit/xunit/issues/1629

### CODE REVIEW

**Comment by anurse** [comment]
@bradwilson you able to take a quick look? We'd like to try this out to fix an issue we're seeing in some tests, and having a build on your MyGet would be the easiest way to do that :)

**Comment by anurse** [comment]
🎉

**Comment by BrennanConroy** [comment]
Would it be possible to push a preview build with this to your MyGet feed?

**Comment by bradwilson** [comment]
Yeah, sorry about that. I changed the build # format slightly, and that caused MyGet to delete every package that got uploaded after the change. A month ago. Thanks MyGet. 😝

**Comment by bradwilson** [comment]
Build is on MyGet: `2.4.0-beta.1.build3945`. Took a little while to clean up MyGet, and then the code signing service disappeared for a bit. 🙄

**Pull request merged**
