### PR TITLE
Use T4.BuildTools for TheoryData related classes

### PR DESCRIPTION
**Pull request by TheConstructor**
Follow up to https://social.tchncs.de/@TheConstructor/113410911624322896 to illustrate usage of T4.BuildTools around TheoryData. Aim is to provide the same content as before, but only write the code once and have T4.BuildTools loop it out into the actual code.

As one type-parameter has special code for TheoryDataRow and TheoryData (no ValueTuple needed/possible), I did not include it in the generation, but left it untouched.

Note: At times I encountered the need to have more type-arguments to TheoryData, and am generating up until 15 type-parameters of TheoryDataRow and TheoryData. This matches with Func<> that also ships with up to 15 type-parameters. If this is unacceptable, I can easily adjust the code to only generate up until 10 type-parameters.

### CODE REVIEW

**Comment by TheConstructor** [comment]
@dotnet-policy-service agree

**Comment by bradwilson** [comment]
The build fails for me inside Visual Studio:

```
1>------ Build started: Project: xunit.v3.core, Configuration: Debug Any CPU ------
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zxwuvfec.q4w\TheoryDataRow.n.tt(12,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zxwuvfec.q4w\TheoryDataRow.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zxwuvfec.q4w\TheoryDataRow.n.tt(14,73): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zxwuvfec.q4w\TheoryDataRow.n.tt(55,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-iwac0len.igv\TheoryData.n.tt(12,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-iwac0len.igv\TheoryData.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-iwac0len.igv\TheoryData.n.tt(14,73): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-iwac0len.igv\TheoryData.n.tt(82,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(41,163): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(41,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(41,165): error CS1010: Newline in constant
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(42,33): error CS1010: Newline in constant
1>c:\Users\bradwilson\AppData\Local\Temp\t4-zpakhzsf.dar\MatrixTheoryData.n.tt(72,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ervs1whk.rg4\TheoryDataRow.n.tt(12,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ervs1whk.rg4\TheoryDataRow.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ervs1whk.rg4\TheoryDataRow.n.tt(14,73): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ervs1whk.rg4\TheoryDataRow.n.tt(55,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ge0pe5rs.ocw\TheoryData.n.tt(12,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ge0pe5rs.ocw\TheoryData.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ge0pe5rs.ocw\TheoryData.n.tt(14,73): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-ge0pe5rs.ocw\TheoryData.n.tt(82,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(13,79): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(41,163): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(41,164): error CS1056: Unexpected character '$'
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(41,165): error CS1010: Newline in constant
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(42,33): error CS1010: Newline in constant
1>c:\Users\bradwilson\AppData\Local\Temp\t4-hbsjljgc.aim\MatrixTheoryData.n.tt(72,164): error CS1056: Unexpected character '$'
```

Is there something required to make this work inside Visual Studio 2022?

**Comment by bradwilson** [comment]
Looks like the version of T4 transformation used by Visual Studio is different than the one used by `dotnet build`, and the Visual Studio version is using an older version of C#. Maybe that's overridable?

**Comment by bradwilson** [comment]
Verified, the version of C# used in the built-in T4 support is C# 5 and cannot be upgraded. Some simple template changes can fix that.

I'm making those changes right now, but unfortunately your branch does not allow me to push to it.

**Comment by bradwilson** [comment]
Since I can't push my changed up into your branch, I'm going to merge my tweaks to your PR myself through a push (with you credited), but I won't be able to mark this PR as merged as a result.

**Comment by bradwilson** [comment]
Merged via https://github.com/xunit/xunit/commit/923310ab07598fec7a1ce4fd6872693485626ebf, thanks!

**Comment by bradwilson** [comment]
Also, I upped MatrixTheoryData to 15, because why not? 😂

**Comment by TheConstructor** [comment]
Looks good, would have hoped, that there was an easy way to deactivate `.tt`-processing in Visual Studio, but searching for one sounded, like there wasn't. `T4.BuildTools` easily goes beyond C#5. But hey, in the end the generated file is way more important, and it should still ease the maintenance of these rather repetitive code-sections

**Comment by bradwilson** [comment]
I actually prefer the TT processing in Visual Studio to be enabled, since I can open the .tt and .cs side by side and watch the changes in real time every time the .tt file is saved. 😄

**Pull request closed without merging**
