### PR TITLE
Generated list of assertions.

### LINKED ISSUE #1901: Documentation: List of assertions and their meanings
As a continuation of #1762, there would be great value in a page listing all the possible assertions (`Assert....`), and their purpose.

[This page](https://xunit.github.io/docs/comparisons) has some of the information, but the focus is on comparing xUnit's assertions with assertions in other testing frameworks, which means that assertions which don't have a corresponding syntax in the other testing frameworks will not appear on the list.

### PR DESCRIPTION
**Pull request by gnerkus**
To resolve #1901 

- Generate Markdown metadata via DocFX
- Add Markdown file to `site` directory of `gh-pages` branch

The built page looks like this locally:

assertions_screenshot

### CODE REVIEW

**Comment by gnerkus** [comment]
@dotnet-policy-service agree

**Comment by bradwilson** [comment]
How is this being generated? I will need to be able to update the docs from time to time (and wouldn't mind going back and back-filling some of the recently shipped versions).

Thanks!

**Comment by gnerkus** [comment]
> How is this being generated? I will need to be able to update the docs from time to time (and wouldn't mind going back and back-filling some of the recently shipped versions).
> 
> Thanks!

These were generated using a global installation of _DocFx_. I'll outline the steps.

1. I made a copy of the repo and checked the copy into the `gh-pages` branch. I worked with two repos (locallly):
    - `xunit` checked out to `main`
    - `xunit` checked out to `gh-pages` _(called this xunit-docs)_
2. I installed _DocFx_ and initialized it in the original repo. This created a `docfx.json` config file in the root directory.
3. I modified the `src` attribute of the config to point to the `xunit.v3.assert` project.
_docfx.json_
```json
{
        "metadata": [
            {
            "src": [
                {
                "src": "./src/xunit.v3.assert",
                "files": [
                    "**/*.csproj"
                ]
                }
            ],
            "dest": "api",
            }
        ],
        "build": {
            "content": [
            {
                "files": [
                "**/*.{md,yml}"
                ],
                "exclude": [
                "_site/**"
                ]
            }
            ],
            "resource": [
            {
                "files": [
                "images/**"
                ]
            }
            ],
            "output": "_site",
            "template": [
            "default",
            "modern"
            ],
            "globalMetadata": {
            "_appName": "xunit",
            "_appTitle": "xunit",
            "_enableSearch": true,
            "pdf": false
            }
        }
    }
``` 
4. I enabled markdown output with `docfx metadata --outputFormat markdown`. See [here](https://github.com/dotnet/docfx/pull/9232) for more information.
    - I opted for the markdown output because the generated `yml` files relied heavily on CSS and JS files that had also been generated. These would have interfered with the existing styling.
5. I copied the generated markdown files into the `xunit-docs` repo (the one checked out to the `gh-pages` branch).

**Comment by bradwilson** [comment]
Given that, this is likely already covered by #2916.

**Pull request closed without merging**
