### PR TITLE
Further fix handling of invalid chars + add tests

### PR DESCRIPTION
**Pull request by jamesqo**
This pull request add tests for the changes introduced in xunit/assert.xunit#1 and xunit/assert.xunit#2. It also fixes the original issue as defined in #804, and updates the Git submodule for Asserts.

cc @bradwilson

### CODE REVIEW

**Comment by jamesqo** [comment]
@bradwilson, thanks for merging my other PR. I've finished working on this one, could you please take a look? (Unfortunately I wasn't able to refactor it to use `ArgumentFormatter.Format`, since it truncates past 50 characters, but on the bright side the CI build seems to be passing.)

**Comment by hughbe** [comment]
Just a friendly ping - what's the progress on this?

**Comment by bradwilson** [comment]
Sorry, we haven't had any time to work on xUnit since this PR was pushed. We haven't forgotten about you, though. :)

**Comment by hughbe** [comment]
Nice to see this merged. @bradwilson how often does xunit's Nuget package update so I can make some changes following on this PR in dotnet/corefx

**Comment by jamesqo** [comment]
@hughbe

> how often does xunit's Nuget package update so I can make some changes following on this PR in dotnet/corefx

This version of xunit isn't actually used in corefx FYI, the one in [dotnet/buildtools](https://github.com/dotnet/buildtools) is. You'd have to wait for the .NET Core team to merge dotnet/buildtools#565 over there (which I've just reopened since this has been merged), and then update the [buildtools version](https://github.com/dotnet/corefx/blob/master/BuildToolsVersion.txt) in corefx to let you make the changes.

**Comment by bradwilson** [comment]
All CI builds are available on MyGet: http://myget.org/gallery/xunit

Those changes went into `2.2.0-beta2-build3284`.

**Comment by hughbe** [comment]
Thanks @jamesqo @bradwilson

**Pull request merged**
