### PR TITLE
Expose ITest as a parameter in BeforeAfterTestAttribute

### PR DESCRIPTION
**Pull request by SimonCropp**
@bradwilson would this be possible to include in v3?

### CODE REVIEW

**Comment by bradwilson** [comment]
In general, I would say "yes", though I'd want to give some thought as to whether that exact set of parameters is the right thing. For example, if we go down the path of [creating a text context object](https://github.com/xunit/xunit/issues/621), maybe it makes more sense to pass the text context there (and thus keep the signature simple at a single parameter).

**Comment by SimonCropp** [comment]
do u want test context to be an interface?

**Comment by bradwilson** [comment]
I'm gonna merge this as-is and deal with the test context stuff at a later time.

**Comment by bradwilson** [comment]
Because of the spaces to tabs conversion I had to hand-merge this, and committed it as 94f514ea.

Thanks!

**Pull request closed without merging**
