### PR TITLE
Changing DelegatingSummarySink and DelegatingXmlCreationSink to invok…

### PR DESCRIPTION
**Pull request by jonlegendre**
Changing `DelegatingSummarySink` and `DelegatingXmlCreationSink` to invoke` innerSink.OnMessage` after local handling of messages.

fixing #2090 and maybe #1534

Note I tried to only invoke the local `HandleTestAssemblyFinished` after `innerSink.OnMessage` per the comment in #2090 
> We could move the inner sink invocation down as you suggest, with the caveat that we call HandleTestAssemblyFinished after the inner sink has had a chance to run.

However, this did not pass unit tests nor fix the issue.

The current changes I have made do pass all unit tests and also pass the test from https://github.com/sobkowicz/xunit-sink-xml-app.

I don't love the new unit test I added, and I am uncertain if you will like the location of the new class made to facilitate the test. Honestly I am not sure this test adds value, but it does demonstrate that the innerSink.OnMessage is invoked successfully as part of the process.

If this is accepted I will make a similar PR for V2.

### CODE REVIEW

**Comment by bradwilson** [comment]
There is an issue with the test setup, specifically the implementation of `ExecutionSinkThatFillsExecutionSummaryWhenOnMessageInvoked.OnMessage`.

The problem with this setup is that it doesn't correctly mimic the behavior of DelegatingSummarySink. It will record an execution summary regardless of what message is sent to it, and in your test you send two messages. So you've accidentally side-stepped the race condition by creating the execution summary (at the wrong time) because of the `_ErrorMessage`.

If instead of the fake type, we use this code to set up a real instance of DelegatingSummarySink:

```csharp
var project = new XunitProject();
var assembly = new XunitProjectAssembly(project);
var discoveryOptions = _TestFrameworkOptions.ForDiscovery();
var executionOptions = _TestFrameworkOptions.ForExecution();
var innerSink = Substitute.For<_IMessageSink>();
IExecutionSink localSink = new DelegatingSummarySink(assembly, discoveryOptions, executionOptions, AppDomainOption.Disabled, false, innerSink);
```

Doing that instead causes the test to fail like I would've expected, because of the ordering problem:

```
DelegatingXmlCreationSinkTests.AddsAssemblyFinishedInformationToXmlWhenSummaryIsFilledByOnMessage[en-US] [FAIL]
Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "2112"
Actual:   "0"
           ↑ (pos 0)
```

**Comment by bradwilson** [comment]
I'm going to see if I can update the tests on `main` and `v2` to use a real instance of the `DelegatingSummarySink` so that they can properly illustrate the behavior.

**Comment by bradwilson** [comment]
I pushed the unit test change into `main`, merged `main` into your branch, and deleted the test you added (since it's no longer necessary, as the test above is now already using the real XmlSummarySink). The test now fails appropriately.

I think this fundamentally illustrates the ordering problem: do the right thing for the race condition by moving the inner sink invocation to the bottom, and it breaks `DelegatingXmlCreationSink`.

I'm still thinking about ways to solve this that don't involve breaking changes and/or duplicated types.

**Comment by jonlegendre** [comment]
closing for now. I am thinking on it as well.

**Pull request closed without merging**
