### PR TITLE
Fix #1924: Enumerable equal assert

### LINKED ISSUE #1924: Assert.Equal for long arrays cuts of the actual difference
E.g.

```cs
Assert.Equal(
    new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" },
    new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "RUBBISH" }
)
``` 

We get an assertion failure, but it only starts from the start of the array and not where the failure occurs. I propose something like for strings:
```cs
Assert.Equal(
    "This is a very long string and I'm interested in it's full value, before and after.",
    "This is a very long string and |I'm interested in it's full value, before and after."
);
```
```
Message: Assert.Equal() Failure
                                 ↓ (pos 31)
Expected: ···ery long string and I'm interested in it's full value, before···
Actual:   ···ery long string and |I'm interested in it's full value, befor···
                                 ↑ (pos 31)
```

### PR DESCRIPTION
**Pull request by daveMueller**
Closes #1924

### CODE REVIEW

**Comment by daveMueller** [comment]
Don't know why the build fails. I would be grateful if someone could help me out.

**Comment by bradwilson** [comment]
Because this change depends on the other change being merged first, it will naturally fail until that other merge takes place. It's nothing to be concerned about, as I usually hand-merge them both on my box when doing verification.

**Comment by bradwilson** [comment]
This was automatically closed when the primary branch was renamed to `main`. Please re-base your PR to the new branch name and re-open. Sorry for the inconvenience! For more information: https://twitter.com/xunit/status/1269842273509863425

**Comment by bradwilson** [comment]
Thanks! This was recently merged with https://github.com/xunit/assert.xunit/commit/bb5d19df7322627f649e55e8006157cd0af31ac6 and https://github.com/xunit/xunit/commit/f4be18e8bf926b3ec0ead036fca5df7fb2114116 and as such, this PR is now redundant, so I'm closing it.

**Pull request closed without merging**
