### PR TITLE
add -noskips switch to console runner

### PR DESCRIPTION
**Pull request by jhamm**
When flag is set and skips exist, it will report the skips and add that
number to the failures.
For the all outputs, the failure reason will be FAIL_SKIP to indicate why
the test failed.

PR for #367

### CODE REVIEW

**Comment by bradwilson** [comment]
Thanks for this PR.

There were a couple things I ended up not 100% sure on when I evaluated it; the biggest one is that tests are double counted (they are counted as a skip as well as a failure). I'm thinking the best solution might be an intercepting message bus that converts skips to failures so that the rest of the pipeline does not need to be changed. It's something I'd want to play around with to see if I like it, but I don't have time to do that today so this is going to have to wait for the next beta.

**Comment by jhamm** [comment]
I understand your comment of the double counting. This was done on purpose because the test falls in both categories when the flag is set, but I can see how this could be misleading.

I can take a look at using the Message Bus approach to see if that is better.

**Comment by jhamm** [comment]
I update the PR based on your suggestions. You are right the first commit didn't follow SRP. I think this one is better.

**Comment by bradwilson** [comment]
Sorry it took me so long to get to this. I had to do some surgery on it to get it to compile because of the code changes that have happened in the intervening time.

I renamed the console switch to `-failskips` rather than `-noskips` because that seemed to better reflect its purpose. I also added the functionality into the MSBuild runner, triggered by adding `FailSkips="true"` to the `<xunit>` task.

Everything has been merged with commit 9bee623.

Thanks again!

**Pull request closed without merging**
