### PR TITLE
allow assembly level BeforeAfterTestAttribute

### PR DESCRIPTION
**Pull request by SimonCropp**
thoughts on this one? and if u like it, is it something you want an explicit test for?

### CODE REVIEW

**Comment by bradwilson** [comment]
Yeah, I think this would be fine. I'm definitely planning to try to enable more assembly-level stuff in v3. I would consider tests to be required. ;) But I don't think they'd be too complex to add.

**Comment by SimonCropp** [comment]
ok i will push a test to this branch

**Comment by bradwilson** [comment]
Ping on adding a test, am ready to merge otherwise. Thanks! 👍🏼

**Comment by bradwilson** [comment]
(also, apologies in advance for the merge conflicts from spaces vs. tabs ☹️)

**Pull request closed without merging**
