### PR TITLE
remove some redundant type checks

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@bradwilson i know this is a minor change, happy to have it closed if u dont think it is worth it

**Comment by bradwilson** [comment]
I haven't been regularly merging PRs in the mainline because of the v3 work. That said, there's no reason not to merge this.

**Comment by bradwilson** [comment]
Thanks!

**Comment by SimonCropp** [comment]
Thank you for xunit

**Pull request merged**
