### PR TITLE
Allow MemberData methods and properties to be discovered on interfaces as well as classes

### PR DESCRIPTION
**Pull request by JamesTerwilliger**
Unit tests hopefully to follow

This PR allows properties and methods referenced by a MemberData attribute to be discovered on interfaces as well as derived classes.

Intended to address https://github.com/xunit/xunit/issues/2799

### CODE REVIEW

**Comment by JamesTerwilliger** [comment]
@bradwilson It's odd, I tried writing a test for this, but I couldn't get the test runner to pick up the test I wrote in this PR.

**Comment by JamesTerwilliger** [comment]
(The test added in the PR currently is not the only approach I tried, I did several things all gated on NET70 or higher and all failed to pick up the test somehow. What's in the PR is just the commonality between all of what I tried.)

**Comment by bradwilson** [comment]
I've updated the test and push the change.

**Comment by bradwilson** [comment]
I assume this makes it ready to go? Or did you have something else in mind?

**Comment by JamesTerwilliger** [comment]
@bradwilson If the test passes, it's ready to go!

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
