### PR TITLE
Implement ToString on DiagnosticMessage

### PR DESCRIPTION
**Pull request by 0xced**
My hope is that the diagnostics will become available in JetBrains Rider unit test logs. Currently, we can see messages like this: `TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage`. My intuition is that the Rider test runner is calling `ToString()` on `Xunit.Sdk.DiagnosticMessage` and that implementing `ToString()` will get the actual diagnostic messages in the Rider logs.

Anyway, implementing `ToString()` in a class that wraps a message string can't hurt.

```
09:14:44.304 |I| TestRunner: XUnitRunner Execution started 
09:14:44.310 |I| TestRunner: Discoverer Discovering tests from ~/Projects/MyApp/MyApp.Tests/bin/Debug/netcoreapp3.1/MyApp.Tests.dll 
09:14:44.550 |V| TestRunner: Discoverer Sending discovery results to server... 
09:14:44.602 |V| Run: 9aabab47-d5ae-4b6a-b5c5-d137ae8c521f - Discovery result processing started
09:14:44.602 |I| TestRunner: Discoverer Discovery completed 
09:14:44.615 |V| Run: 9aabab47-d5ae-4b6a-b5c5-d137ae8c521f - Discovery result processing finished (+0 -0 ~11)
09:14:44.785 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:45.483 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:45.490 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:45.570 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:45.578 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:51.787 |V| TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage 
09:14:51.810 |I| TestRunner: XUnitRunner Execution completed
```

### CODE REVIEW

**Comment by bradwilson** [comment]
I notice you opened this against the `v2` branch but there are no plans to ship any more v2 versions of xUnit.net.

I'd be happy to merge this into `main` so it'll be part of v3.

**Comment by 0xced** [comment]
OK, I knew you were working on xUnit v3 but I didn't know that there was no more plan for the v2 anymore at all.

I have updated the pull request to target the `main` branch.

**Comment by bradwilson** [comment]
Thanks!

**Comment by 0xced** [comment]
Let's hope it will work as expected in Rider!

Do you have an ETA for the first v3 beta? Or is it already available on a custom NuGet feed?

**Comment by bradwilson** [comment]
NuGet packages aren't available yet because I don't have the new runner system in place. You could take what I have now and build stand-alone unit tests (.EXEs for .NET Framework, `dotnet run`nable for .NET Core), but no way to run several in parallel, and no way to run them in 3rd party places (including Visual Studio). That's the piece that's missing. Don't have an ETA yet, but I'm hoping sometime next month (October) for a first pre-release build.

**Comment by 0xced** [comment]
This is indeed a Rider bug, tracked as [RIDER-60811](https://youtrack.jetbrains.com/issue/RIDER-60811).

While waiting for xUnit v3 to be released, one can workaround this Rider bug by using a `DiagnosticMessage` subclass:

```c#
class PrintableDiagnosticMessage : DiagnosticMessage
{
    public PrintableDiagnosticMessage(string message) : base(message)
    {
    }
    
    public override string ToString() => Message;
}
```

**Comment by 0xced** [comment]
For the record: this pull request was back ported to xUnit.net v2.5.0 and the Rider bug was fixed in Rider 2023.1.

**Pull request merged**
